# Generated by Django 3.2.4 on 2021-06-24 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0002_alter_subtasks_goals'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subtasks',
            options={'ordering': ['complete', 'name'], 'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.AddField(
            model_name='subtasks',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
