# Generated by Django 3.2.4 on 2021-06-28 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0004_subtasks_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtasks',
            name='complete',
            field=models.BooleanField(default=False, verbose_name='Выполнено'),
        ),
        migrations.AlterField(
            model_name='subtasks',
            name='goals',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='to_do_list.tasks', verbose_name='Цель'),
        ),
    ]
